name: Build project

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]


jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          #- StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- StandaloneWindows # Build a Windows standalone.
          #- iOS # Build an iOS player.
          #- Android # Build an Android .apk standalone app.
          #- WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: summer-23-unity/Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          #UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: summer-23-unity
      # NOTE: I think im having issues doing cross platform builds.
      # linux doent recognize operations on the build/${{ matrix.targetPlatform }}.app directory for some reason
      # the fix might be to introduce another build that does MacOC builds on a macos-latest image
      # see: https://game.ci/docs/github/getting-started#workflow-examples
      #- name: Set file permissions
      #  run: |
      #    if [ "StandaloneOSX" == "${{ matrix.targetPlatform }}" ]; then
      #      echo "updating permissions on build/${{ matrix.targetPlatform }}.app"
      #      ls -R build
      #      chmod -R 777 build/${{ matrix.targetPlatform }}.app
      #      ls -R build
      #    fi   
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

