


name: main
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: build step
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        targetPlatform: WebGL
